import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApplication,configuration} from '../server/index.mjs';
import {MockProvider,OpenAIProvider} from '../server/provider.mjs';
import {safePinterestURL,validatePlan} from '../server/schema.mjs';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1V8AAAAASUVORK5CYII=','base64');
const imageData='data:image/png;base64,'+png.toString('base64');
async function harness(t,provider=new MockProvider(),overrides={}){const dir=await mkdtemp(join(tmpdir(),'pinwell-test-'));const config={...configuration({AI_PROVIDER:'mock',DATA_DIR:dir,PORT:'3000'}),...overrides};const app=await createApplication(config,provider);await new Promise(r=>app.server.listen(0,'127.0.0.1',r));config.origin='http://127.0.0.1:'+app.server.address().port;const request=async(path,body,key,cookie)=>{const r=await fetch(config.origin+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{Origin:config.origin,...(body===undefined?{}:{'Content-Type':'application/json'}),...(key?{'Idempotency-Key':key}:{}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});const b=await r.json();return {status:r.status,body:b,headers:r.headers}};t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});return {...app,request,config,dir}}
async function waitFor(h,id,status){for(let i=0;i<200;i++){const r=await h.request('projects/'+id);if(r.body.status===status)return r.body;await new Promise(r=>setTimeout(r,10))}throw Error('Timeout waiting for '+status)}
test('two-phase generation, durable images, progress, export, idempotency',async t=>{const h=await harness(t);let r=await h.request('projects',{imageData,title:'Mountain study'},'1234567890123456');assert.equal(r.status,202);const id=r.body.id;let p=await waitFor(h,id,'review');assert.equal(p.stepImages.length,0);assert.equal(p.approved,false);r=await h.request('projects',{imageData},'1234567890123456');assert.equal(r.body.id,id);assert.equal(h.store.list().length,1);r=await h.request('projects/'+id+'/generate',{plan:p.plan});assert.equal(r.status,202);assert.equal((await h.request('projects/'+id+'/generate',{})).status,409);p=await waitFor(h,id,'complete');assert.equal(p.stepImages.length,6);const image=await fetch(h.config.origin+p.stepImages[5]);assert.equal(image.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);assert.equal((await h.request('projects/'+id+'/progress',{completedSteps:[0,1]})).body.completedSteps.length,2);const bundle=(await h.request('projects/'+id+'/export')).body;assert.equal(Object.keys(bundle.images).length,8);assert.equal(bundle.format,'pinwell-ai-project-v1')});
test('no key is a truthful setup state and creates no job',async t=>{const p=new OpenAIProvider({key:''});const h=await harness(t,p);assert.equal((await h.request('status')).body.ready,false);assert.equal((await h.request('projects',{imageData},'1234567890123456')).status,503);assert.equal(h.store.list().length,0)});
test('failed image request resumes only missing images',async t=>{const provider=new MockProvider();let count=0;provider.image=async({reference})=>{if(++count===3)throw Error('fixture failure');return reference.bytes};const h=await harness(t,provider);const id=(await h.request('projects',{imageData},'1234567890123456')).body.id;await waitFor(h,id,'review');await h.request('projects/'+id+'/generate',{});let p=await waitFor(h,id,'failed');assert.equal(p.stepImages.length,1);await h.request('projects/'+id+'/resume',{});p=await waitFor(h,id,'complete');assert.equal(p.stepImages.length,6);assert.equal(count,8)});
test('cancellation while planning still requires review before paid image work',async t=>{let release;const provider=new MockProvider();const plan=provider.plan.bind(provider);provider.plan=async(...args)=>{await new Promise(r=>release=r);return plan(...args)};const h=await harness(t,provider);const id=(await h.request('projects',{imageData},'1234567890123456')).body.id;while(!release)await new Promise(r=>setTimeout(r,5));await h.request('projects/'+id+'/cancel',{});release();await waitFor(h,id,'cancelled');await h.request('projects/'+id+'/resume',{});const p=await waitFor(h,id,'review');assert.equal(p.stepImages.length,0);assert.equal(p.approved,false)});
test('budget ceiling prevents further provider calls',async t=>{const h=await harness(t,new MockProvider(),{limit:1});const id=(await h.request('projects',{imageData},'1234567890123456')).body.id;await waitFor(h,id,'review');await h.request('projects/'+id+'/generate',{});const p=await waitFor(h,id,'failed');assert.match(p.error,/Daily provider-call/);assert.equal(p.finalImage,null)});
test('authentication, origin and source boundaries',async t=>{assert.throws(()=>safePinterestURL('http://127.0.0.1/private'));assert.throws(()=>safePinterestURL('https://i.pinimg.com.evil.test/a'));assert.throws(()=>safePinterestURL('https://i.pinimg.com:999/a'));const h=await harness(t,new MockProvider(),{password:'a-long-test-password'});assert.equal((await h.request('projects')).status,401);const login=await h.request('login',{password:'a-long-test-password'});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await h.request('projects',undefined,undefined,cookie)).status,200);const r=await fetch(h.config.origin+'/api/projects',{method:'POST',headers:{Origin:'https://evil.test',Cookie:cookie}});assert.equal(r.status,403);const bad=await h.request('projects',{imageURL:'https://localhost/private'},'1234567890123456',cookie);assert.equal(bad.status,400);assert.throws(()=>validatePlan({steps:[]}))});
test('startup marks in-flight work interrupted and keeps checkpoints',async t=>{const h=await harness(t);h.store.put({id:'00000000-0000-4000-8000-000000000000',status:'rendering',stepImages:['saved'],completedSteps:[0]});const app=await createApplication(h.config,new MockProvider());assert.equal(app.store.get('00000000-0000-4000-8000-000000000000').status,'interrupted');assert.deepEqual(app.store.get('00000000-0000-4000-8000-000000000000').stepImages,['saved']);app.store.close()});
test('provider request contracts and image reference ordering without network',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const mock=new MockProvider(),reference={bytes:png,type:'image/png'},opts={medium:'Acrylic',difficulty:'Beginner',shape:'Square'},plan=await mock.plan(reference,opts),calls=[];globalThis.fetch=async(url,init)=>{calls.push({url,init});return {ok:true,json:async()=>url.endsWith('/responses')?{status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(plan)}]}]}:{data:[{b64_json:png.toString('base64')}]} }};const provider=new OpenAIProvider({key:'test-not-real',textModel:'gpt-4.1',imageModel:'gpt-image-1.5',quality:'medium'});await provider.plan(reference,opts);await provider.image({reference,final:reference,previous:reference,plan,opts,index:2});const request=JSON.parse(calls[0].init.body);assert.equal(request.store,false);assert.equal(request.text.format.type,'json_schema');assert.match(request.input[0].content[1].image_url,/^data:image\/png;base64,/);assert.equal(calls[1].init.body.getAll('image[]').length,3);assert.equal(calls[1].init.body.get('n'),'1')});
test('completed canvases save idempotently and material checks persist independently',async t=>{const h=await harness(t);const id=(await h.request('projects',{imageData},'canvaspatch123456')).body.id;await waitFor(h,id,'review');assert.equal((await h.request('projects/'+id+'/canvas',{})).status,409);assert.equal((await h.request('projects/'+id+'/materials',{item:'Water jar',checked:true})).status,200);await h.request('projects/'+id+'/generate',{});await waitFor(h,id,'complete');const a=(await h.request('projects/'+id+'/canvas',{})).body;const b=(await h.request('projects/'+id+'/canvas',{})).body;assert.equal(a.savedAt,b.savedAt);assert.equal(b.savedCanvas,true);assert.deepEqual(b.materialsChecked,['Water jar']);assert.equal(b.stepImages.length,6);await h.request('projects/'+id+'/materials',{item:'Water jar',checked:false});assert.deepEqual(h.store.get(id).materialsChecked,[]);assert.equal((await h.request('projects/'+id+'/materials',{item:'bad',checked:'yes'})).status,400)});
