import http from 'node:http';
import {createDibbyMCP} from './dibby-mcp.mjs';
import {readFile,writeFile,mkdir,rename,stat} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID,randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import {Store} from './store.mjs';
import {AppError,options,validatePlan,imageType,safePinterestURL} from './schema.mjs';
import {OpenAIProvider,MockProvider} from './provider.mjs';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
export function configuration(env=process.env){const host=env.HOST||'127.0.0.1',port=Number(env.PORT||3000),origin=env.PUBLIC_ORIGIN||`http://127.0.0.1:${port}`,password=env.APP_PASSWORD||'';if(!['127.0.0.1','::1','localhost'].includes(host)&&password.length<16)throw Error('Non-loopback hosting requires APP_PASSWORD with at least 16 characters.');const provider=env.AI_PROVIDER||'openai';if(!['mock','openai'].includes(provider))throw Error('AI_PROVIDER must be openai or mock.');if(!['low','medium','high'].includes(env.IMAGE_QUALITY||'medium'))throw Error('Invalid IMAGE_QUALITY.');const limit=Number(env.MAX_PROVIDER_CALLS_PER_DAY||40);if(!Number.isInteger(limit)||limit<1)throw Error('Invalid provider-call limit.');return {host,port,origin:new URL(origin).origin,password,dataDir:resolve(env.DATA_DIR||join(root,'data')),publicDir:join(root,'public'),publicCatalog:env.DIBBY_PUBLIC_CATALOG==='true',provider,limit,key:env.OPENAI_API_KEY||'',textModel:env.OPENAI_TEXT_MODEL||'gpt-4.1',imageModel:env.OPENAI_IMAGE_MODEL||'gpt-image-1.5',quality:env.IMAGE_QUALITY||'medium'};}
export async function createApplication(config,providerOverride){
 const store=new Store(config.dataDir),provider=providerOverride||(config.provider==='mock'?new MockProvider():new OpenAIProvider(config)),media=join(config.dataDir,'media');await mkdir(media,{recursive:true});
 const dibby=await createDibbyMCP(config);
 const queue=new Set(),creating=new Set(),sessions=new Map(),attempts=new Map();let busy=false,stopping=false,active=null;
 for(const p of store.list()){if(['planning','rendering','queued-plan','queued-images'].includes(p.status)){p.status='interrupted';p.error='The server stopped during generation. Completed images are saved. Resume may repeat the last provider request and incur another charge.';store.put(p)}}
 const assetPath=(id,name)=>join(media,id,name),assetURL=(id,name)=>`/api/projects/${id}/images/${name}`;
 async function saveImage(p,name,bytes){if(bytes.length>25*1024*1024)throw new AppError('Generated image is too large.',502);imageType(bytes);await mkdir(join(media,p.id),{recursive:true});await writeFile(assetPath(p.id,name)+'.tmp',bytes);await rename(assetPath(p.id,name)+'.tmp',assetPath(p.id,name));return assetURL(p.id,name)}
 async function loadImage(p,name){const bytes=await readFile(assetPath(p.id,name));return {bytes,type:imageType(bytes)}}
 function checkCancelled(p){const current=store.get(p.id);if(stopping||current?.cancelRequested)throw new AppError('Generation cancelled. Completed images are preserved.',409)}
 async function providerCall(p,fn){checkCancelled(p);store.reserve(config.limit);const controller=new AbortController();active=controller;const timer=setTimeout(()=>controller.abort(),300000);try{return await fn(controller.signal)}finally{clearTimeout(timer);active=null}}
 function checkpoint(p){const current=store.get(p.id);p.cancelRequested=current?.cancelRequested||false;p.completedSteps=current?.completedSteps||p.completedSteps;p.materialsChecked=current?.materialsChecked||p.materialsChecked;return store.put(p)}
 async function processQueue(){if(busy||stopping)return;busy=true;try{while(queue.size&&!stopping){const id=queue.values().next().value;queue.delete(id);const p=store.get(id);if(!p||p.cancelRequested)continue;try{
  const reference=await loadImage(p,'reference');
  if(!p.plan){p.status='planning';p.error='';checkpoint(p);p.plan=await providerCall(p,s=>provider.plan(reference,p.options,s));checkCancelled(p);p.status='review';checkpoint(p);continue}
  if(!p.approved){p.status='review';checkpoint(p);continue}
  p.status='rendering';p.error='';checkpoint(p);
  if(!p.finalImage){const bytes=await providerCall(p,s=>provider.image({reference,plan:p.plan,opts:p.options,index:null},s));p.finalImage=await saveImage(p,'final',bytes);checkpoint(p);checkCancelled(p)}
  const final=await loadImage(p,'final');
  for(let i=0;i<6;i++){if(p.stepImages[i])continue;checkCancelled(p);p.currentStep=i+1;checkpoint(p);const previous=i?await loadImage(p,'step-'+i):null;const bytes=await providerCall(p,s=>provider.image({reference,final,previous,plan:p.plan,opts:p.options,index:i},s));p.stepImages[i]=await saveImage(p,'step-'+(i+1),bytes);checkpoint(p);checkCancelled(p)}
  p.status='complete';p.currentStep=6;checkpoint(p);
 }catch(e){const latest=store.get(id);p.status=latest?.cancelRequested?'cancelled':stopping?'interrupted':'failed';p.cancelRequested=latest?.cancelRequested||false;p.error=e instanceof AppError?e.message:e.name==='AbortError'?'The request timed out or was cancelled. The provider may have charged for it. Completed images are saved.':e.message?.startsWith('Daily provider-call')?e.message:'Generation could not finish. Completed images are saved. You can resume manually.';checkpoint(p)}}}finally{busy=false}}
 const enqueue=p=>{queue.add(p.id);void processQueue()};
 function send(res,status,value,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(type==='application/json'?JSON.stringify(value):value)}
 async function body(req,max=12*1024*1024){if(Number(req.headers['content-length']||0)>max)throw new AppError('Request is too large.',413);let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>max)throw new AppError('Request is too large.',413);chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new AppError('Invalid JSON.')}}
 async function referenceFrom(b){let bytes;if(b.imageData){const match=String(b.imageData).match(/^data:image\/(?:png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new AppError('Upload a PNG, JPEG, or WebP image.');bytes=Buffer.from(match[1],'base64')}else{const response=await fetch(safePinterestURL(b.imageURL),{redirect:'error',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new AppError('The reference could not be downloaded. Upload a saved copy instead.');const reader=response.body.getReader();let size=0;const chunks=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>8*1024*1024){await reader.cancel();throw new AppError('Reference must be under 8 MB.')}chunks.push(value)}bytes=Buffer.concat(chunks)}if(bytes.length>8*1024*1024)throw new AppError('Reference must be under 8 MB.');return {bytes,type:imageType(bytes)}}
 const loginPage=`<!doctype html><meta name="viewport" content="width=device-width"><title>The Midnight Palette — Sign in</title><style>body{font:18px system-ui;max-width:420px;margin:15vh auto;padding:24px;background:#111819;color:#eee5d3}h1{font:36px Georgia,serif;color:#d9c08b}p{color:#c0b49e}input{background:#1c2526;color:#eee5d3;border:1px solid #595847}input,button{font:inherit;padding:12px;width:100%;box-sizing:border-box;margin:8px 0}button{background:#c6ac76;color:#111819;border:0;border-radius:8px}</style><h1>The Midnight Palette</h1><p>Your new 2am Obsession.</p><p>Enter your app password.</p><form><input type="password" name="password" autocomplete="current-password" required aria-label="App password"><button>Sign in</button></form><p role="alert" id="error"></p><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:e.target.password.value})});if(r.ok)location.href='/';else document.getElementById('error').textContent='Sign-in failed. Check your password or try later.'}</script>`;
 const server=http.createServer(async(req,res)=>{try{
  if(req.headers.host!==new URL(config.origin).host)throw new AppError('Unrecognized host. Set PUBLIC_ORIGIN to the URL you use.',403);
  const requestPath=new URL(req.url,config.origin).pathname;
  if(requestPath==='/mcp'&&config.publicCatalog)return await dibby(req,res);
  if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==config.origin)throw new AppError('Requests must come from this app.',403);
  if(req.headers['sec-fetch-site']==='cross-site')throw new AppError('Cross-site requests are not allowed.',403);
  const url=new URL(req.url,config.origin),path=url.pathname;
  if(path==='/api/login'&&req.method==='POST'){const b=await body(req,4096),ip=req.socket.remoteAddress,now=Date.now();let a=attempts.get(ip)||{count:0,until:now+600000};if(a.until<now)a={count:0,until:now+600000};if(a.count>=10)throw new AppError('Try again in ten minutes.',429);a.count++;attempts.set(ip,a);const hash=v=>createHash('sha256').update(v).digest();if(!config.password||!timingSafeEqual(hash(String(b.password||'')),hash(config.password)))throw new AppError('Invalid password.',401);attempts.delete(ip);for(const [k,v] of sessions)if(v<Date.now())sessions.delete(k);const token=randomBytes(32).toString('hex');sessions.set(token,Date.now()+86400000);res.setHeader('Set-Cookie',`pinwell_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=86400${config.origin.startsWith('https:')?'; Secure':''}`);return send(res,200,{ok:true})}
  if(config.password){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pinwell_session='))?.slice(16);if(!token||!(sessions.get(token)>Date.now())){if(path.startsWith('/api/'))throw new AppError('Sign in to continue.',401);return send(res,401,loginPage,'text/html; charset=utf-8')}}
  if(path==='/api/status'&&req.method==='GET')return send(res,200,{ready:provider.ready,mock:provider.mock,provider:config.provider,models:{text:config.textModel,image:config.imageModel},dailyCallLimit:config.limit});
  if(path==='/api/projects'&&req.method==='GET')return send(res,200,{projects:store.list()});
  if(path==='/api/projects'&&req.method==='POST'){
   if(!provider.ready)throw new AppError('AI is not connected yet. Add OPENAI_API_KEY to the server .env file and restart.',503);
   const b=await body(req);const key=req.headers['idempotency-key'];if(typeof key!=='string'||!/^[A-Za-z0-9-]{16,100}$/.test(key))throw new AppError('A request ID is required.');let existing=store.findRequest(key);if(existing)return send(res,200,store.get(existing));if(creating.has(key))throw new AppError('This request is already being prepared. Retry in a moment.',409);
   if(store.list().filter(p=>['queued-plan','planning','queued-images','rendering'].includes(p.status)).length>=5)throw new AppError('Five projects are already queued. Wait for one to finish.',429);
   creating.add(key);try{const reference=await referenceFrom(b);existing=store.findRequest(key);if(existing)return send(res,200,store.get(existing));
   const p={id:randomUUID(),title:String(b.title||'Untitled painting').slice(0,150),sourcePinId:String(b.sourcePinId||'').slice(0,100),sourceURL:/^https?:\/\//.test(b.sourceURL||'')?String(b.sourceURL).slice(0,2000):'',options:options(b),status:'queued-plan',approved:false,plan:null,finalImage:null,stepImages:[],completedSteps:[],mock:provider.mock,createdAt:new Date().toISOString(),error:'',cancelRequested:false};p.referenceImage=await saveImage(p,'reference',reference.bytes);store.put(p);store.setRequest(key,p.id);enqueue(p);return send(res,202,p)}finally{creating.delete(key)}
  }
  const match=path.match(/^\/api\/projects\/([a-f0-9-]{36})(?:\/(.*))?$/);
  if(match){let p=store.get(match[1]);if(!p)throw new AppError('Project not found.',404);const action=match[2]||'';
   if(!action&&req.method==='GET')return send(res,200,p);
   if(action.startsWith('images/')&&req.method==='GET'){const name=action.slice(7);if(!/^(reference|final|step-[1-6])$/.test(name))throw new AppError('Image not found.',404);try{const im=await loadImage(p,name);return send(res,200,im.bytes,im.type)}catch{throw new AppError('Image not found.',404)}}
   if(action==='export'&&req.method==='GET'){res.setHeader('Content-Disposition',`attachment; filename="pinwell-${p.id}.json"`);const bundle={format:'pinwell-ai-project-v1',project:p,images:{}};for(const name of ['reference','final',...p.stepImages.map((_,i)=>'step-'+(i+1))]){try{const im=await loadImage(p,name);bundle.images[name]=`data:${im.type};base64,${im.bytes.toString('base64')}`}catch{}}return send(res,200,bundle)}
   if(req.method==='POST'&&action==='cancel'){if(['complete','review','failed','interrupted','cancelled'].includes(p.status))throw new AppError('This project is not running.',409);p.cancelRequested=true;queue.delete(p.id);if(!['planning','rendering'].includes(p.status))p.status='cancelled';store.put(p);return send(res,200,p)}
   if(req.method==='POST'&&action==='generate'){
    if(!provider.ready)throw new AppError('Add an API key and restart the server first.',503);
    if(p.status!=='review')throw new AppError('This project is not awaiting review.',409);const b=await body(req,64000);p=store.get(p.id);if(p.status!=='review')throw new AppError('This project is already running.',409);if(b.plan)p.plan=validatePlan(b.plan);p.approved=true;p.cancelRequested=false;p.status='queued-images';store.put(p);enqueue(p);return send(res,202,p);
   }
   if(req.method==='POST'&&action==='resume'){if(!provider.ready)throw new AppError('AI is not connected.',503);if(!['failed','interrupted','cancelled'].includes(p.status))throw new AppError('This project cannot be resumed right now.',409);p.cancelRequested=false;p.status=p.plan?'queued-images':'queued-plan';p.error='';store.put(p);enqueue(p);return send(res,202,p)}
   if(req.method==='POST'&&action==='canvas'){if(p.status!=='complete')throw new AppError('Finish generating the tutorial before saving it as a canvas.',409);p.savedCanvas=true;p.savedAt=p.savedAt||new Date().toISOString();store.put(p);return send(res,200,p)}
   if(req.method==='POST'&&action==='materials'){const b=await body(req,4096);p=store.get(p.id);if(typeof b.item!=='string'||!b.item.trim()||b.item.length>300||typeof b.checked!=='boolean')throw new AppError('Invalid material selection.');const items=new Set(p.materialsChecked||[]);if(b.checked)items.add(b.item);else items.delete(b.item);if(items.size>100)throw new AppError('Too many materials.');p.materialsChecked=[...items];store.put(p);return send(res,200,p)}
   if(req.method==='POST'&&action==='progress'){const b=await body(req,4096);p=store.get(p.id);if(!Array.isArray(b.completedSteps)||b.completedSteps.some(x=>!Number.isInteger(x)||x<0||x>5))throw new AppError('Invalid progress.');p.completedSteps=[...new Set(b.completedSteps)];store.put(p);return send(res,200,p)}
   throw new AppError('Action not found.',404);
  }
  if(path.startsWith('/api/'))throw new AppError('Endpoint not found.',404);
  if(req.method!=='GET'&&req.method!=='HEAD')throw new AppError('Method not allowed.',405);
  const file=resolve(config.publicDir,'.'+decodeURIComponent(path==='/'?'/index.html':path));if(!file.startsWith(config.publicDir+sep))throw new AppError('Not found.',404);let bytes;try{bytes=await readFile(file)}catch{throw new AppError('Not found.',404)}const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp'};send(res,200,req.method==='HEAD'?'':bytes,types[extname(file)]||'application/octet-stream');
 }catch(e){if(!res.headersSent)send(res,e.status||500,{error:e.status?e.message:'The server could not complete this request.'});else res.end()}});
 return {server,store,async close(){stopping=true;active?.abort();await new Promise(r=>server.close(r));while(busy)await new Promise(r=>setTimeout(r,10));store.close()}};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const config=configuration();const app=await createApplication(config);app.server.listen(config.port,config.host,()=>console.log(`The Midnight Palette: ${config.origin}\nAI: ${config.provider==='mock'?'MOCK — test fixtures only':config.key?'configured (not yet verified)':'setup mode — add OPENAI_API_KEY when ready'}`));for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>void app.close().then(()=>process.exit(0)));}
